#!/usr/bin/env bash
#eroor 404 config
#red_to="server_name \$server_addr;\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/;\n\t}\n\tlocation /404 {\n\t\tinternal\n\t}"

apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/error_page.html
red_from="server_name _;"
red_to="server_name \$server_addr;\n\terror_page 404 /error_page.html;\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/;\n\t}"
sed -i "s#$red_from#$red_to#" /etc/nginx/sites-available/default
service nginx restart
