#!/usr/bin/env bash
#configure a second server and balance between two servers
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
red_from="location / {"
red_to="location / {\n\t\tadd_header X-Served-By $hostname;\n"
sed -i "s#$red_from#$red_to#" /etc/nginx/sites-available/default
service nginx restart
