#!/usr/bin/env bash
#this is load balancer config
apt-get install -y haproxy
echo -e "frontend alx_frontend\n\tbind *:80\n\tmode http\n\tdefault_backend alx_backend\nbackend alx_backend\n\tbalance roundrobin\n\tserver 481511-web-01 35.175.129.122:80 check\n\tserver 481511-web-02 34.224.16.6:80 check" >> /etc/haproxy/haproxy.cfg
echo "ENABLED=1" >> /etc/default/haproxy
service haproxy restart
