#!/usr/bin/env  bash
#ssh config
Include /etc/ssh/ssh_config.d/*.conf

Host *
    PasswordAuthentication no
    IdentityFile ~/.ssh/school
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
