#!/usr/bin/env bash
#this is load balancer config
echo -e "frontend alx_frontend\n\tbind *:80\n\tmode http\n\tdefault_backend alx_backend\nbackend alx_backend\n\tbalance roundrobin\n\tserver 481511-web-01 35.175.129.122:80 check\n\tserver 481511-web-02 34.224.16.6:80 check" >> ./test
