#!/usr/bin/env bash
#this is a script printing 10 Best School
i=0;
while [ $i -le 9 ]
do
	echo "Best School"
	i=$((i+1))
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	fi
done
